// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdwgemrcstqfvdozwhws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhkd2dlbXJjc3RxZnZkb3p3aHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTkzOTYsImV4cCI6MjA2NjI5NTM5Nn0.o9HaEu9LvV0AHX6zFSgfaQSXRDxzWspllE94nZIlJQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);